"""Tests for metadata extraction and the central display (Task 6)."""

from __future__ import annotations

import math
import struct
import subprocess
import wave
from pathlib import Path

import pytest

from desktop_music.services.metadata import Metadata, read_metadata
from desktop_music.ui.central_display import (
    PAGE_ALBUM_ART,
    PAGE_SPECTRUM,
    CentralDisplay,
)


# -- fixtures --------------------------------------------------------------


def _write_wav(path: Path, seconds: float = 0.5, rate: int = 8000) -> None:
    n = int(rate * seconds)
    with wave.open(str(path), "w") as w:
        w.setnchannels(1)
        w.setsampwidth(2)
        w.setframerate(rate)
        frames = bytearray()
        for i in range(n):
            frames += struct.pack("<h", int(20000 * math.sin(2 * math.pi * 440 * i / rate)))
        w.writeframes(bytes(frames))


# a tiny valid PNG generated by Qt (guaranteed decodable)
def _make_png() -> bytes:
    from PyQt6.QtCore import QBuffer, QByteArray
    from PyQt6.QtGui import QImage, QColor

    img = QImage(4, 4, QImage.Format.Format_RGB32)
    img.fill(QColor(120, 60, 200))
    ba = QByteArray()
    buf = QBuffer(ba)
    buf.open(QBuffer.OpenModeFlag.WriteOnly)
    img.save(buf, "PNG")
    return bytes(ba.data())


_PNG_1x1 = _make_png()


@pytest.fixture
def tagged_wav(tmp_path) -> str:
    path = tmp_path / "song.wav"
    _write_wav(path)
    from mutagen.wave import WAVE
    from mutagen.id3 import APIC, TALB, TIT2, TPE1

    audio = WAVE(str(path))
    if audio.tags is None:
        audio.add_tags()
    audio.tags.add(TIT2(encoding=3, text="My Title"))
    audio.tags.add(TPE1(encoding=3, text="My Artist"))
    audio.tags.add(TALB(encoding=3, text="My Album"))
    audio.tags.add(APIC(encoding=3, mime="image/png", type=3, desc="", data=_PNG_1x1))
    audio.save()
    return str(path)


@pytest.fixture
def tagged_flac(tmp_path) -> str:
    src = tmp_path / "tone.wav"
    _write_wav(src)
    dst = tmp_path / "song.flac"
    subprocess.run(
        ["ffmpeg", "-y", "-loglevel", "quiet", "-i", str(src), str(dst)],
        check=True,
    )
    from mutagen.flac import FLAC, Picture

    audio = FLAC(str(dst))
    audio["title"] = "Flac Title"
    audio["artist"] = "Flac Artist"
    audio["album"] = "Flac Album"
    pic = Picture()
    pic.type = 3
    pic.mime = "image/png"
    pic.data = _PNG_1x1
    audio.add_picture(pic)
    audio.save()
    return str(dst)


# -- metadata --------------------------------------------------------------


def test_read_metadata_mp3_style_tags(tagged_wav) -> None:
    meta = read_metadata(tagged_wav)
    assert meta.title == "My Title"
    assert meta.artist == "My Artist"
    assert meta.album == "My Album"
    assert meta.duration_ms > 0
    assert meta.cover_art is not None


def test_read_metadata_flac(tagged_flac) -> None:
    meta = read_metadata(tagged_flac)
    assert meta.title == "Flac Title"
    assert meta.artist == "Flac Artist"
    assert meta.cover_art is not None


def test_read_metadata_no_tags(tmp_path) -> None:
    path = tmp_path / "bare.wav"
    _write_wav(path)
    meta = read_metadata(str(path))
    assert meta.title == ""
    assert meta.duration_ms > 0
    assert meta.cover_art is None


def test_sidecar_cover_named_front_case_insensitive(tmp_path) -> None:
    path = tmp_path / "bare.wav"
    _write_wav(path)
    (tmp_path / "FRONT.png").write_bytes(_PNG_1x1)
    meta = read_metadata(str(path))
    assert meta.cover_art == _PNG_1x1


def test_sidecar_cover_prefers_named_over_single(tmp_path) -> None:
    path = tmp_path / "bare.wav"
    _write_wav(path)
    other = b"other-image-bytes"
    (tmp_path / "random.jpg").write_bytes(other)
    (tmp_path / "Cover.png").write_bytes(_PNG_1x1)
    meta = read_metadata(str(path))
    assert meta.cover_art == _PNG_1x1


def test_sidecar_cover_single_image_fallback(tmp_path) -> None:
    path = tmp_path / "bare.wav"
    _write_wav(path)
    data = b"only-one-image"
    (tmp_path / "whatever.jpg").write_bytes(data)
    meta = read_metadata(str(path))
    assert meta.cover_art == data


def test_sidecar_cover_multiple_unnamed_images_no_pick(tmp_path) -> None:
    path = tmp_path / "bare.wav"
    _write_wav(path)
    (tmp_path / "one.jpg").write_bytes(b"a")
    (tmp_path / "two.png").write_bytes(b"b")
    meta = read_metadata(str(path))
    assert meta.cover_art is None


def test_embedded_cover_takes_precedence_over_sidecar(tmp_path) -> None:
    path = tmp_path / "song.wav"
    _write_wav(path)
    from mutagen.wave import WAVE
    from mutagen.id3 import APIC

    audio = WAVE(str(path))
    if audio.tags is None:
        audio.add_tags()
    audio.tags.add(APIC(encoding=3, mime="image/png", type=3, desc="", data=_PNG_1x1))
    audio.save()
    (tmp_path / "cover.png").write_bytes(b"sidecar-should-not-win")
    meta = read_metadata(str(path))
    assert meta.cover_art == _PNG_1x1


def test_read_metadata_bad_file(tmp_path) -> None:
    path = tmp_path / "broken.mp3"
    path.write_bytes(b"not really audio")
    meta = read_metadata(str(path))
    assert isinstance(meta, Metadata)
    assert meta.title == ""


# -- central display -------------------------------------------------------


def test_central_display_pages(qtbot) -> None:
    display = CentralDisplay()
    qtbot.addWidget(display)
    assert display.has_page(PAGE_ALBUM_ART)
    assert display.current_page == PAGE_ALBUM_ART


def test_central_display_add_and_switch(qtbot) -> None:
    from PyQt6.QtWidgets import QLabel

    display = CentralDisplay()
    qtbot.addWidget(display)
    display.add_page(PAGE_SPECTRUM, QLabel("spectrum"))
    display.show_page(PAGE_SPECTRUM)
    assert display.current_page == PAGE_SPECTRUM
    display.show_page(PAGE_ALBUM_ART)
    assert display.current_page == PAGE_ALBUM_ART


def test_album_art_shows_metadata(qtbot) -> None:
    display = CentralDisplay()
    qtbot.addWidget(display)
    meta = Metadata(title="T", artist="A", cover_art=_PNG_1x1)
    display.show_metadata(meta, fallback_title="fallback")
    assert display.album_art.has_art
